import PDFDocument from 'pdfkit';
import { brand, disclosures } from '@machai/config/public';
import { BUREAU_LABELS, type NormalizedReport } from '@machai/types';

/**
 * Renders a report PDF (spec §7.2).
 *
 * Written to private storage and served only through short-lived signed URLs —
 * this document contains the business's full credit file and must never be at a
 * guessable public address.
 *
 * The generated PDF deliberately restates the no-guarantee disclosure: this
 * file gets forwarded to lenders and accountants, so it has to stand on its own
 * without the surrounding UI (spec §14.3).
 */
export async function renderReportPdf(
  report: NormalizedReport,
  businessName: string,
): Promise<Buffer> {
  const doc = new PDFDocument({ size: 'LETTER', margin: 54 });
  const chunks: Buffer[] = [];

  doc.on('data', (chunk: Buffer) => chunks.push(chunk));

  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });

  // Header
  doc.fontSize(9).fillColor('#4a7a5e').text(brand.name.toUpperCase(), { characterSpacing: 1 });
  doc.moveDown(0.4);
  doc.fontSize(20).fillColor('#1c1f1d').text('Business Credit Report');
  doc.moveDown(0.2);
  doc.fontSize(11).fillColor('#5b615d').text(businessName);
  doc
    .fontSize(9)
    .fillColor('#8a908c')
    .text(
      `${BUREAU_LABELS[report.bureau]} · pulled ${report.pulledAt.toLocaleString('en-US', {
        dateStyle: 'long',
        timeStyle: 'short',
      })}`,
    );

  divider(doc);

  // Score
  doc.fontSize(13).fillColor('#1c1f1d').text('Score');
  doc.moveDown(0.3);
  if (report.score !== null) {
    doc.fontSize(34).fillColor('#2f6f4e').text(String(report.score), { continued: true });
    doc.fontSize(11).fillColor('#8a908c').text(`   on ${report.scoreScale}`);
    if (report.scoreBand) {
      doc.moveDown(0.2);
      doc.fontSize(11).fillColor('#4a4f4c').text(report.scoreBand);
    }
  } else {
    doc
      .fontSize(11)
      .fillColor('#4a4f4c')
      .text('This bureau publishes no score for this business at present.');
  }

  divider(doc);

  // Risk factors
  doc.fontSize(13).fillColor('#1c1f1d').text('What is affecting this file');
  doc.moveDown(0.4);
  if (report.riskFactors.length === 0) {
    doc.fontSize(10).fillColor('#6b716d').text('No factors were reported.');
  } else {
    for (const factor of report.riskFactors) {
      const marker = factor.impact === 'positive' ? '+' : factor.impact === 'negative' ? '−' : '·';
      doc
        .fontSize(10)
        .fillColor(factor.impact === 'negative' ? '#9a3b32' : '#3d4340')
        .text(`${marker}  ${factor.summary}`, { indent: 4 });
      doc.moveDown(0.25);
    }
  }

  divider(doc);

  // Tradelines
  doc.fontSize(13).fillColor('#1c1f1d').text('Tradelines on file');
  doc.moveDown(0.4);
  if (report.tradelines.length === 0) {
    doc.fontSize(10).fillColor('#6b716d').text('No tradelines are reported on this file.');
  } else {
    for (const line of report.tradelines) {
      doc.fontSize(10).fillColor('#1c1f1d').text(line.creditorName);
      const parts = [
        line.accountType,
        line.dateOpened ? `opened ${line.dateOpened}` : null,
        line.currentBalanceCents !== null ? `balance ${money(line.currentBalanceCents)}` : null,
        line.creditLimitCents !== null ? `limit ${money(line.creditLimitCents)}` : null,
        line.paymentStatus,
      ].filter(Boolean);
      doc.fontSize(9).fillColor('#6b716d').text(parts.join(' · '), { indent: 8 });
      doc.moveDown(0.35);
    }
  }

  // Public records
  if (report.publicRecords.length > 0) {
    divider(doc);
    doc.fontSize(13).fillColor('#1c1f1d').text('Public records');
    doc.moveDown(0.4);
    for (const record of report.publicRecords) {
      doc
        .fontSize(10)
        .fillColor('#1c1f1d')
        .text(`${record.type}${record.filedOn ? ` · filed ${record.filedOn}` : ''} · ${record.status}`);
      doc.moveDown(0.25);
    }
  }

  // A payload the normalizer did not fully understand is surfaced, not hidden —
  // silently omitting fields would make the document quietly incomplete.
  if (report.unmappedFields.length > 0) {
    divider(doc);
    doc
      .fontSize(9)
      .fillColor('#9a6b2f')
      .text(
        `Note: ${report.unmappedFields.length} field(s) in this bureau's response could not be mapped and are omitted above. The full response is retained and this report can be regenerated.`,
      );
  }

  divider(doc);
  doc.fontSize(8).fillColor('#8a908c').text(disclosures.noGuarantee, { align: 'left' });
  doc.moveDown(0.3);
  doc
    .fontSize(8)
    .fillColor('#8a908c')
    .text(
      `Generated by ${brand.name} on ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}. Data supplied by ${BUREAU_LABELS[report.bureau]}.`,
    );

  doc.end();
  return done;
}

function divider(doc: PDFKit.PDFDocument): void {
  doc.moveDown(0.8);
  doc
    .strokeColor('#e3e6e4')
    .lineWidth(1)
    .moveTo(doc.page.margins.left, doc.y)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .stroke();
  doc.moveDown(0.8);
}

function money(cents: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0,
  }).format(cents / 100);
}
